language: node_js
node_js:
  - '12.10'
  - '10.10'
jdk:
  - oraclejdk8
install:
  - mkdir /tmp/dynamodb
  - wget -O - https://s3-us-west-2.amazonaws.com/dynamodb-local/dynamodb_local_latest.tar.gz | tar xz --directory /tmp/dynamodb
  - npm install
script:
  - npm run coverage
before_script:
  - java -Xms256M -Xmx256M -Xss2M -Djava.library.path=/tmp/dynamodb/DynamoDBLocal_lib -jar /tmp/dynamodb/DynamoDBLocal.jar -sharedDb -inMemory &
  - sleep 3
